views:
  v1/pods:
    columns:
      - NAME
      - PF
      - READY
      - STATUS
      - RESTARTS
      - AGE
      - CPU
      - MEM
      - '%CPU/R'
      - '%CPU/L'
      - '%MEM/R'
      - '%MEM/L'
      - IP
      - NODE
